export const MSG_ADD_TO_CART_SUCCESS='MUA HANG THANH CONG';
export const MSG_UPDATE_CART_SUCCESS='CAP NHAT THANH CONG';
export const MSG_DELETE_PRODUCT_IN_CART_SUCCESS='XOA THANH CONG';
export const MSG_CART_EMPTY='CHUA CO SAN PHAM TRONG GIO HANG';
export const MGS_WELLCOME='XIN CHAO';